Module4 task2
htmlacademy-adaptive/1546623-sedona-20 pull request #7
Opened 2020-08-26 06:25 UTC by HerzogKlaus

2020-08-26 15:23 UTC, Hikikomori commented on source/form.html
> +                Посещенные<br />достопримечательности:
Без `br` никак не обойтись ?

2020-08-26 15:23 UTC, Hikikomori commented on source/less/blocks/find-hotel.less
> +    margin: 0 auto;
Для блоков внешнюю геометрию (отступы, позиционирование и т.д.) задавать нельзя. Делай отступы через родительский блок 
[https://ru.bem.info/methodology/faq/#зачем-внешнюю-геометрию-и-позиционирование-задавать-через-родительский-блок](https://ru.bem.info/methodology/faq/#%D0%B7%D0%B0%D1%87%D0%B5%D0%BC-%D0%B2%D0%BD%D0%B5%D1%88%D0%BD%D1%8E%D1%8E-%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8E-%D0%B8-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA)

Относится ко всем блокам

2020-08-26 15:23 UTC, Hikikomori commented on source/less/blocks/form.less
> +  .form-fieldsets {
Выглядит как отдельный блок. Значит должен быть в отдельном файле

2020-08-26 15:23 UTC, Hikikomori commented on source/less/blocks/form.less
> +  .form-fieldsets__item--atraction .form__legend {
Один блок не должен зависеть от другого

2020-08-26 15:23 UTC, Hikikomori commented on source/less/blocks/form.less
> +  .form-fieldsets__item--atraction .form__line {
И тут

2020-08-27 05:52 UTC, HerzogKlaus commented on source/less/blocks/find-hotel.less
> +    margin: 0 auto;
А find-hotel разве не родительский блок? Выше него только враппер стоит.

2020-08-27 07:07 UTC, Hikikomori commented on source/less/blocks/find-hotel.less
> +    margin: 0 auto;
Ну вот значит враппер это и есть родительский. Да хоть body в конце концов, суть одна, у блоков внешней геометрии быть не должно

2020-08-28 05:48 UTC, Hikikomori requested changes

2020-08-28 05:48 UTC, Hikikomori commented on source/less/blocks/form-fieldsets.less
> +    .form__line {
Я же вроде говорил, что один блок не должен быть зависим от другого. Так не пойдет

2020-08-28 06:34 UTC, HerzogKlaus commented on source/form.html
> +                Посещенные<br />достопримечательности:
Не получилось без br

2020-08-28 06:35 UTC, HerzogKlaus commented on source/less/blocks/find-hotel.less
> +    margin: 0 auto;
Ок, исправил

2020-08-29 11:28 UTC, merged